# Generated by Django 2.2 on 2018-11-06 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicManager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Dispatcher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DecimalField(decimal_places=0, max_digits=4)),
                ('end', models.DecimalField(decimal_places=0, max_digits=4)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('altitude', models.DecimalField(decimal_places=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineSupply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('hospital', models.CharField(max_length=200)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='supply')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=200)),
                ('items', models.TextField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('priority', models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='L', max_length=1)),
                ('status', models.CharField(choices=[('QP', 'Queued for Processing'), ('PW', 'Processing by Warehouse'), ('QD', 'Queued for Dispatch'), ('DI', 'Dispatched'), ('DE', 'Delivered')], default='QP', max_length=2)),
                ('timeQP', models.DateTimeField()),
                ('timePW', models.DateTimeField(null=True)),
                ('timeQD', models.DateTimeField(null=True)),
                ('timeDI', models.DateTimeField(null=True)),
                ('timeDE', models.DateTimeField(null=True)),
                ('clinic_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASP.ClinicManager')),
            ],
        ),
        migrations.AddField(
            model_name='clinicmanager',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ASP.Location'),
        ),
    ]
