# Generated by Django 2.2 on 2018-11-06 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ASP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distance',
            name='end',
        ),
        migrations.RemoveField(
            model_name='distance',
            name='start',
        ),
    ]
