# Generated by Django 2.2 on 2018-11-06 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ASP', '0002_auto_20181106_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='distance',
            name='start',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ASP.Location'),
            preserve_default=False,
        ),
    ]
