# Generated by Django 2.2 on 2018-11-06 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ASP', '0003_distance_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance',
            name='start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_start', to='ASP.Location'),
        ),
    ]
