# Generated by Django 2.2 on 2018-11-06 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ASP', '0004_auto_20181106_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='distance',
            name='end',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='location_end', to='ASP.Location'),
            preserve_default=False,
        ),
    ]
